services:
  - type: web
    name: psihologist-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python psiholog_bot.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_PANEL_USER
        sync: false
      - key: ADMIN_PANEL_PASSWORD
        sync: false
